### ISSUE TITLE
update MS account password

### ISSUE THREAD

**Issue by ayed3** [geoffreylagaisse/Hass-Microsoft-Graph#10]
the integration was working great till I change my MS account password, is this password has anything to do with this integration ?

**Comment by geoffreylagaisse** [comment]
Normally not. Maybe your company changed it policy and invalidated the generated clientid and secret?

**Comment by ayed3** [comment]
I found that Certificate was expired so I issued new one but when I tried it , it gives me this error

Sorry, but we’re having trouble signing you in.

AADSTS700016: Application with identifier '************' was not found in the directory '****'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.

**Comment by geoffreylagaisse** [comment]
Does the applicationid still exist in azure? 

URL: https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationsListBlade

**Comment by ayed3** [comment]
@geoffreylagaisse thanks alot , the certificate was expired and I have created new one and it works again, 

usually the application ID is the one under the application it self not the ID associated with certificate 

now it is working

thanks

**Comment by geoffreylagaisse** [comment]
Np. Here to help.
