### ISSUE TITLE
Question... Is External URL required?

### ISSUE THREAD

**Issue by sean-scott-lr** [geoffreylagaisse/Hass-Microsoft-Graph#12]
I have not configured my HA installation to be available on the internet.  The instructions state:

Add https://<EXTERNAL_HOME_ASSISTANT_URL>:PORT/auth/external/callback

How is this used?  Does it have to be externally reachable ?

**Comment by geoffreylagaisse** [comment]
Yes it is required to be external, because the authentication token needs to be passed to the home assistant API once in a while.
