### ISSUE TITLE
No Sensors

### ISSUE THREAD

**Issue by vcdx71** [geoffreylagaisse/Hass-Microsoft-Graph#13]
Just configured this, was able to authenticate to my account but no sensors show up. ![image](https://github.com/geoffreylagaisse/Hass-Microsoft-Graph/assets/16821128/eeb77131-4070-40ad-b0fc-217dfde0a9b3)

Am I supposed to add something to configuration.yaml

**Comment by geoffreylagaisse** [comment]
Hi this should work without adding something in the configuration.yaml
Strangely enough I never could get the sensor naming correct. But you can update it later on.

Did you follow this part of the guide correctly?

In the left menu, select “API Permissions”
Click “Add a Permission”
Select “Microsoft Graph”
Select “Delegated Permissions”
Search for Presence.Read, expand “Presence” and select “Presence.Read”
Search for User.Read, expand “User” and select “User.Read”
Click the “Add permissions” button

If you did, are you using the business teams of the personal teams. The latter won't work.

**Comment by vcdx71** [comment]
I did, see screenshot. It is business teams.

![image](https://github.com/geoffreylagaisse/Hass-Microsoft-Graph/assets/16821128/58b6827e-11b4-438a-8491-407437377145)

**Comment by geoffreylagaisse** [comment]
Can you check for error logs in the home assistant logging?
If there aren't any enable the debug logging and reload the integration. Then check the logging again.

**Comment by vcdx71** [comment]
Debug log shows:

2024-01-22 15:32:16.419 ERROR (MainThread) [custom_components.microsoft_graph] Error requesting microsoft_graph data: 403, message='Forbidden', url=URL('https://graph.microsoft.com/beta/me/presence')
2024-01-22 15:32:16.420 DEBUG (MainThread) [custom_components.microsoft_graph] Finished fetching microsoft_graph data in 0.051 seconds (success: False)

**Comment by vcdx71** [comment]
Seems Microsoft doesn't allow employees to consent so it doesn't work. Redeployed a new app registration and am getting the needs admin approval consent screen now.

**Comment by geoffreylagaisse** [comment]
So apparently a security option in your tenant.
