### ISSUE TITLE
Issue with multi-factor authentication

### ISSUE THREAD

**Issue by TobiasBitter** [geoffreylagaisse/Hass-Microsoft-Graph#14]
Since the activation of MFA I'm getting this error:
Token request for microsoft_graph failed (invalid_grant): AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access...

Any chance to run this integration with MFA enabled?

**Comment by geoffreylagaisse** [comment]
Strange should work. We also have MFA enabled on our tenant and I was able to receive the authentication token from Microsoft. 
Did you remove the integration and re-added it again after the activation of MFA?
Your security/authentication token could have become invalid at that point.
