### ISSUE TITLE
How to add automations

### ISSUE THREAD

**Issue by scruffy-sjb** [geoffreylagaisse/Hass-Microsoft-Graph#15]
Firstly - I'm new to HA - but not new to Home Automation !!!

I have installed Hass-Microsoft-Graph successfully. 

I now want to add automations to set a light based on my presence.  
My understanding is that I need to start a listener for events before I can create an automation???

Can you tell me what event listener I need to configure in Developer Options?   Or am I totally barking up the wrong tree???

Many thanks,
Simon

**Comment by geoffreylagaisse** [comment]
Hi,

I think you assume something wrong here. I use my integration for exactly the same thing. 
This is how I've setup the automation:
`

> alias: Set Statelight red when calling or do not disturb
> description: ""
> trigger:
>   - platform: state
>     entity_id: sensor.microsoft_teams_activity
>     to: InACall
>   - platform: state
>     entity_id: sensor.microsoft_teams_activity
>     to: DoNotDisturb
>   - platform: state
>     entity_id: sensor.microsoft_teams_activity
>     to: Presenting
> condition:
>   - condition: state
>     entity_id: person.geoffrey_lagaisse
>     state: home
> action:
>   - service: light.turn_on
>     data:
>       brightness_pct: 40
>     target:
>       entity_id: light.state_light
> mode: single

`

**Comment by scruffy-sjb** [comment]
No - I don't think anything is wrong.  Just my lack of understanding of HA.

What I done yesterday was I mirrored the status over to Hubitat and created the automation there triggered on status change - works perfectly.

Many thanks,
Simon

**Comment by geoffreylagaisse** [comment]
You Can also trigger on status change in HA. The hop to hubitat makes it more complicated then it should be :-p
