### ISSUE TITLE
Not an issue, just an FYI

### ISSUE THREAD

**Issue by loryanstrant** [geoffreylagaisse/Hass-Microsoft-Graph#2]
Just saw this pop up in HACS as a new repository, but wondered if you were aware of this one: https://github.com/RogerSelwyn/O365-HomeAssistant

Works quite well, and can be whittled down to only show Teams presence if required.
Have done a write-up of it here: https://www.loryanstrant.com/2022/03/04/microsoft-teams-home-assistant-graph-take-your-presence-to-the-next-level/
(And next level of madness here: https://www.loryanstrant.com/2022/04/25/automatically-raise-your-desk-when-joining-a-microsoft-teams-call-or-meeting/)

**Comment by geoffreylagaisse** [comment]
Hi @loryanstrant 

I did know about the o365 integration, but from before the Prescence logic was added. I didn't follow it anymore afterwards.
I was already using the integration I forked from, starting last year and saw it wouldn't work anymore in HA 2022.05.
Tried searching for relevant replacements and ultimately took matters in own hands. 

Thanks for the heads-up.
